### PR TITLE
Wrote retrieve or retrain function.

### LINKED ISSUE #6: RunResult class
The retrain or retrieve function has a lot of potential return values. Proposed to make it return a class containing all of them, as well as some information about what steps were taken (was retrained, was retrieved, etc)

### PR DESCRIPTION
**Pull request by Peder2911**

### CODE REVIEW

**Comment by Peder2911** [comment]
@hhegre , after looking at your code I rewrote the `RunMyModels` function, now called `views_runs.operations.retrain_or_retrieve` with a few key differences:

* Simplified (no FI in this function, it should be a separate function)
* In-function queryset retrieval (optional preprocessing)
* More automatic filling-out of various metadata forms (queryset name, ex)
* Documentation and type annotations

This function is inspired by the way you are handling models in your code, as pieces of data. It is intended to make the work of "retraining or retrieving" even more declarative. Otherwise, it is quite similar.

Please have a look, and tell me if this works for you! Using this function would certainly make it a bit easier for me to help you with your notebook. As you can see, I wrote a stub for the `hurdle_feature_importances` function that I could implement as well.

**Comment by Peder2911** [comment]
If you want to try out this function before we merge the pull request, do the following:
```
git clone --branch feature/production_operations https://github.com/prio-data/views_runs
pip install views_runs
```
That gives you access to the in-development functions.

**Comment by Peder2911** [comment]
I'll write a quick script that shows how to use this new function.

**Comment by Peder2911** [comment]
See example here: https://github.com/prio-data/views_runs/blob/91614dd7b805d8ba538f8faaf11c7ea8d8129c4a/examples/do_a_run.py

**Comment by Peder2911** [comment]
Added a RunResult class that is used to manage the various outputs of performing a run (`ViewsRun`, `ModelMetadata`, dataset, whether run was retrained, etc).

**Comment by jimdale** [comment]
> If you want to try out this function before we merge the pull request, do the following:
> 
> ```
> git clone --branch feature/production_operations https://github.com/prio-data/views_runs
> pip install views_runs
> ```
git clone --branch feature/production_operations https://github.com/prio-data/views_runs
pip install views_runs

So, this fails to install the branch for me -  I did this instead:

pip install git+https://github.com/prio-data/views_runs@feature/production_operations

but I guess pip install . would have worked?

Anyway, this does install it, but when I try to run do_a_run.py, I get

Traceback (most recent call last):
  File "/Users/jim/Work/ViEWS/ViEWS3/predicting_fatalities/notebooks/do_a_run.py", line 13, in <module>
    run, data = operations.retrain_or_retrieve(
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/operations.py", line 72, in retrain_or_retrieve
    return run_result.RunResult.retrain_or_retrieve(
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/run_result.py", line 144, in retrain_or_retrieve
    exists = store.exists_with_metadata(storage_name, metadata)
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/storage.py", line 155, in exists_with_metadata
    exists = self.exists(name)
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/views_runs/storage.py", line 138, in exists
    return self._model_object_store.exists(name)
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/views_storage/key_value_store.py", line 28, in exists
    return self.backend.exists(key)
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/views_storage/backends/azure.py", line 62, in exists
    return self._blob_client(key).exists()
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/azure/core/tracing/decorator.py", line 83, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/azure/storage/blob/_blob_client.py", line 1155, in exists
    process_storage_error(error)
  File "/Users/jim/opt/anaconda3/envs/viewser/lib/python3.9/site-packages/azure/storage/blob/_shared/response_handlers.py", line 177, in process_storage_error
    exec("raise error from None")   # pylint: disable=exec-used # nosec
  File "<string>", line 1, in <module>
azure.core.exceptions.ClientAuthenticationError: Operation returned an invalid status 'Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.'
ErrorCode:AuthenticationFailed
 
which means my config is wrong, I assume:

_sensitive output of `viewser config dump`_                                           
  
....?

**Comment by Peder2911** [comment]
Hey Jim!

Just a reminder; I am no longer leading development on this project, so I can't give guarantees that I will be following up issues that you post going forward. This is such a quick fix, however, that I thought I would drop you a line.

First of all, do not post the results of `viewser config dump` to Github. As you can see, the output contains several pieces of information that can be considered sensitive. Consider this the equivalent of sharing your password! ;)

Luckily, your issue here is that the Azure storage key is most likely outdated. Ask Håvard og Mihai to give you their key, they can retrieve it with `viewser config get AZURE_BLOB_STORAGE_ACCOUNT_KEY` and set it on your own instance of viewser with `viewser config set AZURE_BLOB_STORAGE_ACCOUNT_KEY $THEIR_KEY`.

Good luck!

**Pull request merged**
